# This YAML file contains secret objects,
# which are necessary to run csi cinder plugin.

kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud.conf: W0dsb2JhbF0KYXV0aC11cmwgPSBodHRwOi8va2V5c3RvbmUub3BlbnN0YWNrLnN2Yy5jbHVzdGVyLmxvY2FsL3YzCmFwcGxpY2F0aW9uLWNyZWRlbnRpYWwtaWQ9MTgyODNmOTU1Yzk1NDcxNmFjN2Q2NTliODU0ZTc4NDUKYXBwbGljYXRpb24tY3JlZGVudGlhbC1zZWNyZXQ9NDV1TGl6UDVfMzk5NWRjWmtIMk5IM1lpMFlMZUJPbmZDMmJMdGZQTldDejVBalZXSGlxNlRwSFJ0ZUVZdTBNcVlpS1VfZmxqdzh4akF1ZWJhVkk2b2cKcmVnaW9uPVJlZ2lvbk9uZQpbQmxvY2tTdG9yYWdlXQpicy12ZXJzaW9uPXYyCmlnbm9yZS12b2x1bWUtYXo9VHJ1ZQo=
